version: '3'

services:
  notebook:
    image: jupyter/scipy-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - F:\DataScience\code\GoldPrices\src\main.ipynb
    environment:
      - JUPYTER_ENABLE_LAB=yes

  webapp:
    image: my-web-app:latest
    ports:
      - "80:80"

networks:
  default:
    external:
      name: my_network
